name: docker build push trivy scanning
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
    docker_build_push:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
               repository: '${{ secrets.CHECKOUT_REPO }}'
         
          - name: Login to DockerHub
            uses: azure/docker-login@v1
            with:
              login-server: githubactionregistory.azurecr.io
              username: ${{ secrets.ACR_USERNAME }}
              password: ${{ secrets.ACR_PASSWORD }}
              
          - name: Build Container image
            run: docker build -t ${{ secrets.ACR_REPO }}:${{ github.run_number }} .
          

          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@master
            with:
                  image-ref: '${{ secrets.ACR_REPO }}:${{ github.run_number }}'
                  format: 'sarif'
                  output: 'trivy-results.sarif'
        
          - name: Upload Trivy scan results to GitHub Security tab
            uses: github/codeql-action/upload-sarif@v2
            with:
                sarif_file: 'trivy-results.sarif'
          
          - name: Publish Docker image
            run: docker push ${{ secrets.ACR_REPO }}:${{ github.run_number }}
