name: GGshield
on:
  workflow_call:
jobs:
  security_scan:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: '${{ secrets.CHECKOUT_REPO }}'

      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
      
      - name: Git_guardian
        uses: GitGuardian/ggshield-action@v1.20.0
        env:
            GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
            GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
            GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
            GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
            GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        continue-on-error: true
